### ISSUE TITLE
Assembly.Load throw exception

### ISSUE THREAD

**Issue by chucklu** [chucklu/DependentChecker#4]
>  Could not load file or assembly 'assembly name' or one of its dependencies. An attempt was made to load a program with an incorrect format.

might need to use the following code to fix this issue
```C#
   internal static Assembly GetAssemblyByName(AssemblyName assemblyName)
		{
			Assembly assembly = GetFirstOrDefaultAssembly(assemblyName.FullName);
			if (assembly == null)
			{
				assembly = Assembly.Load(assemblyName);
			}

			return assembly;
		}

	private static Assembly GetFirstOrDefaultAssembly(string fullName)
		{
			Assembly[] assemblies = AppDomain.CurrentDomain.GetAssemblies();
			return assemblies.FirstOrDefault(a => a.FullName == fullName);
		}
```

**Comment by chucklu** [comment]
We need to use another method to load assembly 
```C#
 internal static Assembly GetAssemblyByFile(string fileName)
        {
            var assembly = Assembly.ReflectionOnlyLoadFrom(fileName);
            if (assembly == null)
            {
                throw new FileNotFoundException(fileName);
            }

            return assembly;
        }
```

**Comment by chucklu** [comment]
2021-09-29 17:37:46.408 +08:00 [ERR] Load assembly [LISA.Batch.CustomInstaller, Version=6.3.0.25091, Culture=neutral, PublicKeyToken=null] failed, System.BadImageFormatException: Could not load file or assembly 'LISA.Batch.CustomInstaller, Version=6.3.0.25091, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: 'LISA.Batch.CustomInstaller, Version=6.3.0.25091, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at DependentChecker.Helper.AssemblyHelper.LoadAssembly(AssemblyName assemblyName) in C:\workspace\GitHub\ChuckLu\chucklu\DependentChecker\DependentChecker\Helper\AssemblyHelper.cs:line 46

\=== Pre-bind state information ===
LOG: Where-ref bind. Location = C:/workspace/Software/UK/UK.Batch/LISA.Batch.CustomInstaller.dll
LOG: Appbase = file:///C:/workspace/GitHub/ChuckLu/chucklu/DependentChecker/DependentChecker/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
\===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\workspace\GitHub\ChuckLu\chucklu\DependentChecker\DependentChecker\bin\Debug\DependentChecker.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Attempting download of new URL file:///C:/workspace/Software/UK/UK.Batch/LISA.Batch.CustomInstaller.dll.
ERR: Failed to complete setup of assembly (hr = 0x8007000b). Probing terminated.

**Comment by chucklu** [comment]
If I switch to ReflectionOnlyLoad(this method without from), it will throw another exception fro another file
2021-09-29 18:21:50.120 +08:00 [ERR] System.IO.FileLoadException: Could not load file or assembly 'C:\\workspace\\Software\\UK\\UK.Batch\\RDC.Controls.Calendar.dll' or one of its dependencies. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
File name: 'C:\\workspace\\Software\\UK\\UK.Batch\\Accor.RDC.Controls.Calendar.dll'
   at System.Reflection.AssemblyName.nInit(RuntimeAssembly& assembly, Boolean forIntrospection, Boolean raiseResolveEvent)
   at System.Reflection.RuntimeAssembly.CreateAssemblyName(String assemblyString, Boolean forIntrospection, RuntimeAssembly& assemblyFromResolveEvent)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.ReflectionOnlyLoad(String assemblyString)
   at DependentChecker.MainWindow.FindDependent(String dependencyPath) in C:\workspace\GitHub\ChuckLu\chucklu\DependentChecker\DependentChecker\MainWindow.xaml.cs:line 137
   at DependentChecker.MainWindow.DependencyChoose_Click(Object sender, RoutedEventArgs e) in C:\workspace\GitHub\ChuckLu\chucklu\DependentChecker\DependentChecker\MainWindow.xaml.cs:line 39

**Comment by chucklu** [comment]
ReflectionOnlyLoadFrom works fine.
